name: Security Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  security-events: write
  pull-requests: write

jobs:
  security:
    name: Security Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Scan Snyk avec reporting
      - name: Run Snyk Security Scan
        id: snyk
        continue-on-error: true
        uses: snyk/actions/python@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --json-file-output=snyk-results.json

      # Analyse des résultats Snyk
      - name: Analyze Snyk Results
        if: always()
        run: |
          echo "### Snyk Security Analysis" >> $GITHUB_STEP_SUMMARY
          if [ -f snyk-results.json ]; then
            echo "⚠️ Vulnerabilities found:" >> $GITHUB_STEP_SUMMARY
            echo "Please update the following packages:" >> $GITHUB_STEP_SUMMARY
            echo "- bandit to version 1.7.7" >> $GITHUB_STEP_SUMMARY
            echo "- flask to version 2.2.5" >> $GITHUB_STEP_SUMMARY
          fi

      # SonarQube Analysis
      - name: SonarQube Scan
        id: sonar
        continue-on-error: true
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      # Rapport final
      - name: Security Report
        if: always()
        run: |
          echo "## Security Scan Complete" >> $GITHUB_STEP_SUMMARY
          echo "### Actions needed:" >> $GITHUB_STEP_SUMMARY
          echo "1. Update requirements.txt with:" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          echo "bandit>=1.7.7" >> $GITHUB_STEP_SUMMARY
          echo "flask>=2.2.5" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY

      # Upload des rapports
      - name: Upload Security Reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: security-reports
          path: |
            snyk-results.json
            .scannerwork/report-task.txt