name: Security Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install bandit safety pytest-cov

    - name: Run unit tests with coverage
      run: |
        pytest tests/ --cov=app --cov-report=xml

    - name: Run Bandit security checks
      run: |
        bandit -r app/ -f json -o bandit-report.json

    - name: Check dependencies for known vulnerabilities
      run: |
        safety check

    - name: Upload security reports
      uses: actions/upload-artifact@v2
      with:
        name: security-reports
        path: |
          bandit-report.json
          coverage.xml

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}